-- this needs to be on top, since everything is resetted with reload
require("ebozkurt.reload")
require("ebozkurt.prefs")
require("ebozkurt.plugins")
require("ebozkurt.keymaps")
require("ebozkurt.telescope")
require("ebozkurt.treesitter")
require("ebozkurt.lualine")
require("ebozkurt.nvim-tree")
require("ebozkurt.comment")
require("ebozkurt.harpoon")
-- todo: for some reason this fails on reload, investigate later
-- require("ebozkurt.colorizer")
require("ebozkurt.possession")
require("ebozkurt.gitsigns")
require("ebozkurt.neogit")
require("ebozkurt.vim-gh-line")
require("ebozkurt.lsp")
require("ebozkurt.luasnip")
require("ebozkurt.themes")
require("ebozkurt.session")

