right_format = """$time"""

[time]
disabled = true
format = '[\[ $time \]]($style) '
time_format = '%T'

[[battery.display]]
threshold = 30

[git_metrics]
disabled = false

[gcloud]
disabled = true

[terraform]
format = "[$symbol$version $workspace]($style) "

[custom.enabled-states]
command = "cat ~/.local/state/state-switcher/enabled_state_icons.txt 2>/dev/null"
shell = "sh"
when = "true"
format = "[$output]($style) "

[custom.gcloud]
command = """ gcloud config list account --format "value(core.account)" | xargs echo """
# this works and it is the method that starship is using, but it is slow and inaccurate at times
# command = """ cat ~/.config/gcloud/configurations/config_$(cat ~/.config/gcloud/active_config) | grep 'account =' | sed -e 's/account = //' """
disabled = true
when = "~/Documents/bitbar_plugins/helpers/check_workdir_subdir.sh"
format = "☁️ [$output]($style) "

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "
