# Generated by nixos-generate-config on the UTM aarch64 VM. Regenerate with
# `nixos-generate-config --root /mnt --show-hardware-config` if the VM disk changes.
{
  lib,
  ...
}: {
  imports = [];

  boot.initrd.availableKernelModules = ["virtio_pci" "xhci_pci" "usbhid" "usb_storage"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/28e8d200-a7bb-48cb-9958-98a9cb86fe19";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5F8D-3BAE";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
