general {
    hide_cursor = false
}

background {
    monitor =
    color = rgba(17, 17, 27, 1.0)
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(205, 214, 244, 1.0)
    font_size = 112
    position = 0, 135
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] whoami
    color = rgba(205, 214, 244, 0.72)
    font_size = 24
    position = 0, 42
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgba(205, 214, 244, 0.72)
    font_size = 20
    position = 0, 250
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 340, 62
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(69, 71, 90, 1.0)
    inner_color = rgba(24, 24, 37, 1.0)
    font_color = rgba(205, 214, 244, 1.0)
    fade_on_empty = false
    placeholder_text = Password
    fail_text = Authentication failed
    position = 0, -80
    halign = center
    valign = center
}

shape {
    monitor =
    size = 124, 44
    color = rgba(49, 50, 68, 0.78)
    rounding = 12
    border_size = 1
    border_color = rgba(137, 180, 250, 0.38)
    position = -150, -170
    halign = center
    valign = center
    onclick = systemctl suspend
}

label {
    monitor =
    text = Sleep
    color = rgba(205, 214, 244, 1.0)
    font_size = 15
    position = -150, -170
    halign = center
    valign = center
    onclick = systemctl suspend
}

shape {
    monitor =
    size = 124, 44
    color = rgba(49, 50, 68, 0.78)
    rounding = 12
    border_size = 1
    border_color = rgba(137, 180, 250, 0.38)
    position = 0, -170
    halign = center
    valign = center
    onclick = systemctl reboot
}

label {
    monitor =
    text = Restart
    color = rgba(205, 214, 244, 1.0)
    font_size = 15
    position = 0, -170
    halign = center
    valign = center
    onclick = systemctl reboot
}

shape {
    monitor =
    size = 124, 44
    color = rgba(49, 50, 68, 0.78)
    rounding = 12
    border_size = 1
    border_color = rgba(243, 139, 168, 0.5)
    position = 150, -170
    halign = center
    valign = center
    onclick = systemctl poweroff
}

label {
    monitor =
    text = Shutdown
    color = rgba(245, 194, 231, 1.0)
    font_size = 15
    position = 150, -170
    halign = center
    valign = center
    onclick = systemctl poweroff
}
